name: ci

on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - uses: GabrielBB/xvfb-action@master
        with:
          run: npm run test -- --coverage
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.os }}
          parallel: true
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
